# Generated by Django 4.1.7 on 2023-03-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CropName', models.CharField(max_length=225)),
                ('PesticideUsed', models.CharField(max_length=225)),
                ('MarketValue', models.CharField(max_length=10)),
                ('Disease', models.CharField(blank=True, max_length=225, null=True)),
                ('Season', models.CharField(max_length=225)),
                ('Photo', models.ImageField(upload_to='crops/images')),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
    ]
