# Generated by Django 4.1.7 on 2023-03-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropdetail',
            name='Photo',
            field=models.ImageField(upload_to='crops/assets/crops'),
        ),
    ]
