# Generated by Django 4.1.7 on 2023-04-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_alter_cropdetail_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropdetail',
            name='Photo',
            field=models.ImageField(upload_to='crops/assets/equipments'),
        ),
    ]
