# Generated by Django 4.1.7 on 2023-03-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_alter_cropdetail_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropdetail',
            name='Photo',
            field=models.ImageField(upload_to='static/assets/crops'),
        ),
    ]
