# Generated by Django 4.1.7 on 2023-03-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_alter_cropdetail_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmerKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=225)),
                ('MiddleName', models.CharField(max_length=225)),
                ('LastName', models.CharField(max_length=225)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Others')], max_length=50)),
                ('MaritualStatus', models.CharField(choices=[('S', 'Single'), ('M', 'Married')], max_length=225)),
                ('Nationality', models.CharField(max_length=225)),
                ('Residential', models.CharField(choices=[('NR', 'Non Resident'), ('F', 'Foreign National')], max_length=50)),
                ('FatherName', models.CharField(max_length=225)),
                ('MotherName', models.CharField(max_length=225)),
                ('GrandfatherName', models.CharField(max_length=225)),
                ('GrandMotherName', models.CharField(max_length=225)),
                ('SpouseName', models.CharField(max_length=225)),
                ('SonName', models.CharField(max_length=225)),
                ('DaughterName', models.CharField(max_length=225)),
                ('Country', models.CharField(max_length=225)),
                ('District', models.CharField(max_length=225)),
                ('Province', models.CharField(max_length=225)),
                ('Municipality', models.CharField(max_length=225)),
                ('WardNo', models.CharField(max_length=225)),
                ('Street', models.CharField(max_length=225)),
                ('PassportPhoto', models.ImageField(upload_to='static/assets/docs')),
                ('CitizenProof', models.CharField(choices=[('C', 'Citizenship'), ('P', 'Passport')], max_length=50)),
                ('FrontPic', models.ImageField(upload_to='static/assets/docs')),
                ('BackPic', models.ImageField(upload_to='static/assets/docs')),
            ],
        ),
    ]
