# Generated by Django 4.1.7 on 2023-03-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_farmerkyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerkyc',
            name='Varify',
            field=models.BooleanField(default=False),
        ),
    ]
