# Generated by Django 4.1.7 on 2023-04-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_farmer_kyc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_kyc',
            name='Dob',
            field=models.DateField(),
        ),
    ]
