# Generated by Django 4.1.7 on 2023-05-10 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_alter_farmer_kyc_daughtername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_kyc',
            name='Passport',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d+(-\\d+)*$')]),
        ),
    ]
