# Generated by Django 4.1.7 on 2023-04-30 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_rename_user_farmer_kyc_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer_kyc',
            old_name='UserId',
            new_name='UserId_id',
        ),
    ]
