# Generated by Django 4.1.7 on 2023-04-30 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_rename_userid_farmer_kyc_userid_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer_kyc',
            old_name='UserId_id',
            new_name='user',
        ),
    ]
