# Generated by Django 4.1.7 on 2023-04-30 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0008_rename_userid_id_farmer_kyc_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer_kyc',
            old_name='user',
            new_name='UserId',
        ),
    ]
