# Generated by Django 4.1.7 on 2023-05-08 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=225)),
                ('pesticide_used', models.CharField(max_length=225)),
                ('market_value', models.CharField(max_length=10)),
                ('disease', models.CharField(blank=True, max_length=225, null=True)),
                ('season', models.CharField(max_length=225)),
                ('crop_img', models.ImageField(upload_to='images/crops')),
                ('description', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
