# Generated by Django 4.1.7 on 2023-05-01 19:37

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(max_length=10, validators=[accounts.models.validate_contact]),
        ),
    ]
