# Generated by Django 4.1.7 on 2023-04-09 06:30

import accounts.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addcrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CropName', models.CharField(max_length=225)),
                ('PesticideUsed', models.CharField(max_length=225)),
                ('MarketValue', models.CharField(max_length=10)),
                ('Disease', models.CharField(blank=True, max_length=225, null=True)),
                ('Season', models.CharField(max_length=225)),
                ('Photo', models.ImageField(upload_to='images/crops')),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(max_length=10, validators=[accounts.models.validate_contact]),
        ),
    ]
