# Generated by Django 4.1.7 on 2023-04-30 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_addcrop_alter_user_contact_farmerkyc'),
        ('accounts', '0002_alter_user_contact'),
    ]

    operations = [
    ]
