# Generated by Django 4.1.7 on 2023-03-25 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_contact'),
        ('accounts', '0002_profile'),
    ]

    operations = [
    ]
