# Generated by Django 4.1.7 on 2023-04-09 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_farmer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='farmerKYC',
            new_name='KYC',
        ),
    ]
