# Generated by Django 4.1.7 on 2023-04-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20230430_1129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addcrop',
        ),
    ]
