# Generated by Django 4.1.7 on 2023-04-09 06:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_farmerkyc_kyc'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmerKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=225)),
                ('MiddleName', models.CharField(max_length=225)),
                ('Last_name', models.CharField(max_length=225)),
                ('Gender', models.CharField(max_length=50)),
                ('MaritualStatus', models.CharField(max_length=50)),
                ('Dob', models.DateField(default=datetime.date.today)),
                ('Nationality', models.CharField(max_length=225)),
                ('Citizenship', models.IntegerField(default=0)),
                ('Password', models.IntegerField(default=0)),
                ('Residential', models.CharField(max_length=50)),
                ('FatherName', models.CharField(max_length=225)),
                ('MotherName', models.CharField(max_length=225)),
                ('GrandfatherName', models.CharField(max_length=225)),
                ('GrandMotherName', models.CharField(max_length=225)),
                ('SpouseName', models.CharField(max_length=225)),
                ('SonName', models.CharField(max_length=225)),
                ('DaughterName', models.CharField(max_length=225)),
                ('Country', models.CharField(max_length=225)),
                ('District', models.CharField(max_length=225)),
                ('Province', models.CharField(max_length=225)),
                ('Municipality', models.CharField(max_length=225)),
                ('WardNo', models.CharField(max_length=225)),
                ('Street', models.CharField(max_length=225)),
                ('PassportPhoto', models.ImageField(upload_to='docs')),
                ('CitizenProof', models.CharField(max_length=50)),
                ('FrontPic', models.ImageField(upload_to='docs')),
                ('BackPic', models.ImageField(upload_to='docs')),
                ('Verify', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='KYC',
        ),
    ]
