# Generated by Django 4.1.7 on 2023-05-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_my_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='my_date',
        ),
    ]
