# Generated by Django 4.1.7 on 2023-04-02 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='addcrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CropName', models.CharField(max_length=225)),
                ('PesticideUsed', models.CharField(max_length=225)),
                ('MarketValue', models.CharField(max_length=10)),
                ('Disease', models.CharField(blank=True, max_length=225, null=True)),
                ('Season', models.CharField(max_length=225)),
                ('Photo', models.ImageField(upload_to='static/assets/crops')),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='farmerKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=225)),
                ('MiddleName', models.CharField(max_length=225)),
                ('Last_name', models.CharField(max_length=225)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Others')], max_length=50)),
                ('MaritualStatus', models.CharField(choices=[('S', 'Single'), ('M', 'Married')], max_length=225)),
                ('Nationality', models.CharField(max_length=225)),
                ('Residential', models.CharField(choices=[('NR', 'Non Resident'), ('F', 'Foreign National')], max_length=50)),
                ('FatherName', models.CharField(max_length=225)),
                ('MotherName', models.CharField(max_length=225)),
                ('GrandfatherName', models.CharField(max_length=225)),
                ('GrandMotherName', models.CharField(max_length=225)),
                ('SpouseName', models.CharField(max_length=225)),
                ('SonName', models.CharField(max_length=225)),
                ('DaughterName', models.CharField(max_length=225)),
                ('Country', models.CharField(max_length=225)),
                ('District', models.CharField(max_length=225)),
                ('Province', models.CharField(max_length=225)),
                ('Municipality', models.CharField(max_length=225)),
                ('WardNo', models.CharField(max_length=225)),
                ('Street', models.CharField(max_length=225)),
                ('PassportPhoto', models.ImageField(upload_to='static/assets/docs')),
                ('CitizenProof', models.CharField(choices=[('C', 'Citizenship'), ('P', 'Passport')], max_length=50)),
                ('FrontPic', models.ImageField(upload_to='static/assets/docs')),
                ('BackPic', models.ImageField(upload_to='static/assets/docs')),
                ('Verify', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
