# Generated by Django 4.1.7 on 2023-04-09 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_farmerkyc_user_alter_farmerkyc_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerkyc',
            old_name='id',
            new_name='user',
        ),
    ]
