# Generated by Django 4.1.7 on 2023-04-27 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_profile'),
        ('accounts', '0009_alter_farmerkyc_backpic_alter_farmerkyc_frontpic_and_more'),
    ]

    operations = [
    ]
