# Generated by Django 4.1.7 on 2023-05-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Article_Photo',
            field=models.ImageField(upload_to='images/article'),
        ),
    ]
