# Generated by Django 4.1.7 on 2023-03-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=155)),
                ('Password', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=500)),
                ('SecondName', models.CharField(max_length=500)),
                ('Email', models.EmailField(max_length=500)),
                ('DOB', models.DateField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('Contact', models.IntegerField()),
                ('Gender', models.CharField(max_length=120)),
                ('Password', models.CharField(max_length=255)),
                ('ConPassword', models.CharField(max_length=255)),
            ],
        ),
    ]
