# Generated by Django 4.1.7 on 2023-03-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='Username',
            new_name='username',
        ),
    ]
