# Generated by Django 4.1.7 on 2023-03-20 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_password_login_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='ConPassword',
            new_name='confirm_password',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='DOB',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='FirstName',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='SecondName',
            new_name='secondName',
        ),
    ]
