# Generated by Django 4.1.7 on 2023-03-20 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_address_registration_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='secondName',
            new_name='second_name',
        ),
    ]
