# Generated by Django 4.1.7 on 2023-03-20 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_firstname_registration_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
