# Generated by Django 4.1.7 on 2023-05-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipments',
            name='MarketValue',
            field=models.CharField(max_length=200),
        ),
    ]
