# Generated by Django 4.1.7 on 2023-04-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_rename_manufacturedyear_addquipments_manufacturedyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EquipmentName', models.CharField(max_length=225)),
                ('ManufacturedYear', models.CharField(max_length=225)),
                ('MarketValue', models.CharField(max_length=10)),
                ('Condition', models.CharField(max_length=225)),
                ('Warrenty', models.CharField(max_length=225)),
                ('Photo', models.ImageField(upload_to='images/equiments')),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
    ]
