# Generated by Django 4.1.7 on 2023-04-27 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_equipments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addquipments',
        ),
    ]
