# Generated by Django 4.1.7 on 2023-04-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0005_alter_equipments_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipments',
            name='Photo',
            field=models.ImageField(upload_to='images/equipments'),
        ),
    ]
